### ISSUE TITLE
Tag latest release v1.7.1

### ISSUE THREAD

**Issue by pSub** [oferkv/phototonic#214]

**Comment by mich181189** [comment]
I'd like to package this for Fedora (Hi, by the way), and having a proper tag rather than just releasing from a SHA would be a massive advantage.

My Fedora ticket is here in case you are interested:
https://bugzilla.redhat.com/show_bug.cgi?id=1332344

**Comment by oferkv** [comment]
Hi, sorry about the delay, Phototonic is not getting attention lately because other commitments...
Will fix this ASAP.

**Comment by oferkv** [comment]
Hi, 
I tagged latest as v1.7.20.

**Comment by barjac** [comment]
That screws up 'git describe' output and breaks my script for making Mageia tarballs - sigh  :(
Is this really necessary?

**Comment by oferkv** [comment]
True, forgot all about that, removed.
mich181189: this can't be set as it messes up dependencies.

**Comment by mich181189** [comment]
Well there's a nice tarball link on the "releases" section now:

https://github.com/oferkv/phototonic/archive/v1.7.20.tar.gz

which is what I need. What exactly did you remove? It looks like there's still a tag for 1.7.20

**Comment by barjac** [comment]
Yes, there is still the "v1.7.20 " tag which is what 'git describe' still outputs :\
@ mich181189
I use this to create the tarball for our Mageia packages, but since this tag was added it's currently broken: http://svnweb.mageia.org/packages/cauldron/phototonic/current/SOURCES/mk-tar-git-rev?revision=814225&view=markup
Nothing fancy but it's quick and easy and has worked for me - I hope it will again when this tag is removed ;)

**Comment by oferkv** [comment]
Sorry, now fixed.

**Comment by barjac** [comment]
git describe changed in the last two commits from
v1.7-19-g3cad33d
to
v1.7.20-1-ga9def1b
so something is still wrong compared to the way it was working.

**Comment by barjac** [comment]
Now fixed - thanks :)
